//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Quantité_produit = new HashSet<Quantité_produit>();
        }
    
        public int id_produit { get; set; }
        public string nom { get; set; }
        public Nullable<decimal> prix { get; set; }
        public string type { get; set; }
        public Nullable<int> nb_produit { get; set; }
        public string description { get; set; }
        public Nullable<int> id_photo { get; set; }
        public Nullable<int> id_catalogue { get; set; }
    
        public virtual Cataloge Cataloge { get; set; }
        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quantité_produit> Quantité_produit { get; set; }
    }
}
