//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quantité_produit
    {
        public int id_qt { get; set; }
        public Nullable<int> quantite_produit { get; set; }
        public Nullable<decimal> prix { get; set; }
        public Nullable<int> id_produit { get; set; }
        public Nullable<int> id_panier { get; set; }
    
        public virtual Panier Panier { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
